version: '3.4'

services:
  # context mongodb
  contextdb:
    container_name: contextdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - contextdb:/data/db
    
    
  # server api
  giftshop-api:
    container_name: giftshop-api
    depends_on:
      - contextdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=giftshop
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/giftshop.pfx
      - MongoSettings:ConnectionString=mongodb://contextdb:27017/
      - MongoSettings:Database=giftshop-demo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.aspnet/https:/https:ro