version: "3.8"

services:
  # server api
  giftshop-api:
    image: giftshop-api:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/.https/localhost.pfx
      - MongoSettings:ConnectionString=mongodb://mongodb:27017/
      - MongoSettings:Database=giftshop-demo
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./Certs:/.https:ro
      - applogs:/app/logs
