version: '3.4'

services:
  # server api
  giftshop-api:
    image: giftshop-api:prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=giftshop
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/giftshop.pfx
      - MongoSettings:ConnectionString=mongodb://mongodb:27017/
      - MongoSettings:Database=giftshop
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.aspnet/https:/https:ro
