version: '3.4'

services:
  # server api
  giftshop-api:
    image: giftshop-api:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=local
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - MongoSettings:ConnectionString=mongodb://mongodb:27017/
      - MongoSettings:Database=giftshop-demo
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
