version: "3.8"

services:
  # mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  # server api
  giftshop-api:
    image: giftshop-api
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: giftshop-api
    depends_on:
      - mongodb

volumes:
  mongodb:
  applogs:
