version: '3.4'

services:
  # contextdb mongodb
  contextdb:
    image: mvertes/alpine-mongo
    

  # server api
  giftshop-api:
    image: giftshop-api:dev
    build:
      context: .
      dockerfile: API/Dockerfile
      
volumes:
  contextdb: