version: '3.4'

services:
  # context mongodb
  contextdb:
    container_name: contextdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - contextdb:/data/db
    
    
  # server api
  giftshop-api:
    container_name: giftshop-api
    depends_on:
      - contextdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=local
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - MongoSettings:ConnectionString=mongodb://contextdb:27017/
      - MongoSettings:Database=giftshop-demo
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https